### ISSUE TITLE
Missing context in message

### ISSUE THREAD

**Issue by melalj** [tjmehta/coworkers-test#4]
I tried to implement your sample code:

``` js
    const data = [ { test: 1 } ];
    coworkersTest(app)
      .send('my-queue-name', JSON.stringify(data))
      .expectAck()
      .expect(done);
```

I get this exception:

```
Uncaught TypeError: Cannot read property 'messageAcked' of undefined
      at EventEmitter.assign.nack (node_modules/coworkers-test/lib/mock-channel-factory.js:25:24)
```

I'm feeling that maybe context is not provided in the message in this line: https://github.com/tjmehta/coworkers-test/blob/master/lib/coworkers-test.js#L58

Any idea?

**Comment by tjmehta** [comment]
I believe the context is added by coworkers itself. I see a similar test case passing here: https://github.com/tjmehta/coworkers-test/blob/master/test/coworkers-test.functional.js#L72 .

Can you add the failing test case and PR it? I will try to fix it.

**Comment by melalj** [comment]
Okay, It looks like it's passing if I do `.send('ack-queue', 'hello world')`

I'm confused about this part of your test:

```
  app.use(function * (next) {
    this.message.content = JSON.stringify(this.message.content)
    yield next
  })
```

Why do you stringify the message?

**Comment by tjmehta** [comment]
I see the error now. It occurs in this tests as well.. it is getting caught by something. Hold on I think I know what is wrong.

**Comment by tjmehta** [comment]
To unblock yourself please change this line:
https://github.com/tjmehta/coworkers-test/blob/master/lib/mock-context-factory.js#L19
to 
`const context = message.context = new Context(app, queueName, message)`

**Comment by tjmehta** [comment]
I am digging into the masked error, and will push a patch very soon.

**Comment by melalj** [comment]
Okay thanks 👍

**Comment by tjmehta** [comment]
coworkers-test was using an outdated property `message.context` which does not exist anymore

**Comment by tjmehta** [comment]
use `coworkers-test@^0.2.0` w/ `coworkers@0.6.x`

**Comment by melalj** [comment]
I changed the line and the test passed 🎉 
That's weird that the tests passed with `coworkers@0.6.1`

**Comment by tjmehta** [comment]
Yeah the tests pass bc the unit tests were covering the api change. In the unit tests most everything was being mocked..

**Comment by tjmehta** [comment]
I had to change a few other line so make sure you use `coworkers-test@0.2.0` that line change alone may still lead to weird test behavior.
